"""
Django settings for polling_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/  

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/  
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Указывает корневую директорию проекта (на уровень выше папки settings.py)
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/  

# SECURITY WARNING: keep the secret key used in production secret!
# Используется для криптографической подписи сессий, токенов и др.
# НИКОГДА не коммить в Git! В продакшене — загружать из переменных окружения.
SECRET_KEY = 'django-insecure-w$%estx3=b&xf@rj1166x%7q4aer4&#ui$4$13rx%=88nw1%1c'

# SECURITY WARNING: don't run with debug turned on in production!
# Включает подробные страницы ошибок (выводит traceback, настройки и т.д.)
# Должно быть False в продакшене — иначе утечка конфиденциальной информации.
DEBUG = True

# Список доменов, с которых разрешено обращаться к сайту.
# При DEBUG=True и пустом списке разрешены: localhost, 127.0.0.1, ::1.
# В продакшене обязательно укажи домен(ы) явно.
ALLOWED_HOSTS = []

# Application definition
# Список всех подключённых приложений: встроенные, сторонние и наши.
INSTALLED_APPS = [
    'django.contrib.admin',        # Админка
    'django.contrib.auth',         # Система аутентификации
    'django.contrib.contenttypes', # Типы моделей
    'django.contrib.sessions',     # Сессии
    'django.contrib.messages',     # Сообщения пользователю
    'django.contrib.staticfiles',  # Работа со статикой (CSS, JS, изображения)
    # Сторонние приложения
    'rest_framework',              # Django REST Framework
    'rest_framework.authtoken',    # Аутентификация по токену (TokenAuthentication)
    'corsheaders',                 # Поддержка CORS (для React-фронтенда)
    # Мои приложения
    'polls',                       # Модели опросов, вопросов, вариантов
    'api',                         # REST API (сериализаторы, views)
]
#INSTALLED_APPS += ['rest_framework.authtoken']  # ← эта строка не нужна, так как уже есть выше

# Последовательность обработки запросов: каждый middleware добавляет функциональность
# (CORS, сессии, CSRF-защита, аутентификация и т.д.)
# Порядок важен! Например, CorsMiddleware должен быть первым.
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',        # ← обрабатывает CORS-заголовки (должен быть первым!)
    'django.middleware.security.SecurityMiddleware', # Защита от некоторых веб-атак
    'django.contrib.sessions.middleware.SessionMiddleware', # Управление сессиями
    'django.middleware.common.CommonMiddleware',     # Общие функции (в т.ч. APPEND_SLASH)
    'django.middleware.csrf.CsrfViewMiddleware',     # Защита от CSRF (межсайтовая подделка запроса)
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Обработка авторизации
    'django.contrib.messages.middleware.MessageMiddleware',    # Сообщения пользователю
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Защита от clickjacking
]

# Главный файл маршрутов (URL-адресов) проекта
ROOT_URLCONF = 'polling_project.urls'

# Настройки шаблонов Django (хотя в REST-проекте они почти не используются)
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],          # Дополнительные папки с шаблонами (не используются в REST)
        'APP_DIRS': True,    # Искать шаблоны внутри папок приложений (в подпапке templates/)
        'OPTIONS': {
            'context_processors': [  # Данные, автоматически передаваемые в каждый шаблон
                'django.template.context_processors.request',  # Доступ к request в шаблоне
                'django.contrib.auth.context_processors.auth', # Данные пользователя
                'django.contrib.messages.context_processors.messages', # Сообщения
            ],
        },
    },
]

# Точка входа для WSGI-сервера (используется при развёртывании)
WSGI_APPLICATION = 'polling_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases  

# Настройки подключения к PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Используем PostgreSQL
        'NAME': 'postgres',                         # Имя базы данных
        'USER': 'postgres',                         # Пользователь БД
        'PASSWORD': '***',                    # Пароль от PostgreSQL 
        'HOST': 'localhost',                        # Адрес сервера БД
        'PORT': '5432',                             # Порт PostgreSQL
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators  

# Правила проверки сложности пароля при регистрации
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/  

LANGUAGE_CODE = 'en-us'  # Язык по умолчанию (для переводов и форматов)
TIME_ZONE = 'UTC'        # Часовой пояс по умолчанию
USE_I18N = True          # Включить интернационализацию (переводы)
USE_TZ = True            # Использовать временные зоны (timezone-aware datetime)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/  

# Префикс URL для статических файлов (например, /static/style.css)
STATIC_URL = 'static/'

# Настройки Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',  # Аутентификация по токену
    ],
}

# Настройки CORS (Cross-Origin Resource Sharing)
# Разрешает фронтенду (React, http://localhost:3000) обращаться к бэкенду (Django)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # Адрес твоего React-приложения
]
# Разрешает отправку учётных данных (cookies, заголовков авторизации) через CORS
# Обязательно для TokenAuthentication, если фронтенд и бэкенд на разных портах
CORS_ALLOW_CREDENTIALS = True 